[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200

# Lisk Mainnet Configuration
[rpc_endpoints]
lisk = "https://rpc.api.lisk.com"

# Network configurations
[profile.default.rpc_endpoints]
lisk = "https://rpc.api.lisk.com"

# Chain configurations (commented out for deployment)
# [etherscan]
# lisk = { key = "${LISK_ETHERSCAN_API_KEY}", url = "https://blockscout.lisk.com/" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
